/*
 * 98Point6 Drop-Token
 *
 * At-home interview implementation of \"98Point6 Drop-Token\" homework assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@focuszonedevelopment.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using static ConnectFour.DataLayer.Models.Game;

namespace ConnectFour.Api.Models.DTOs
{
    /// <summary>
    /// Details of a game in progress
    /// </summary>
    [DataContract]
    public partial class GameDetails
    {
        /// <summary>
        /// Player names
        /// </summary>
        [Required]
        public IEnumerable<string> Players { get; set; }

        /// <summary>
        /// State progress of the game
        /// </summary>
        [Required]
        public GameState State { get; set; }

        /// <summary>
        /// Winning player name, if game is complete
        /// </summary>
        public string Winner { get; set; }
    }
}
