/*
 * 98Point6 Drop-Token
 *
 * At-home interview implementation of \"98Point6 Drop-Token\" homework assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@focuszonedevelopment.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ConnectFour.Api.Models
{
    /// <summary>
    /// Details of a new game
    /// </summary>
    [DataContract]
    public partial class NewGameDetails
    {
        /// <summary>
        /// Player names
        /// </summary>
        [Required]
        public IEnumerable<string> Players { get; set; }

        /// <summary>
        /// Number of columns on the board
        /// </summary>
        [Required]
        public int Columns { get; set; }

        /// <summary>
        /// Number of rows on the board
        /// </summary>
        [Required]
        public int Rows { get; set; }
    }
}
