#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/ConnectFour.Api/ && \
    dotnet build src/ConnectFour.Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/ConnectFour.Api/ConnectFour.Api.csproj --launch-profile web"
