/*
 * 98Point6 Drop-Token
 *
 * At-home interview implementation of \"98Point6 Drop-Token\" homework assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@focuszonedevelopment.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ConnectFour.DataLayer.Models
{
    /// <summary>
    /// Details of a game in progress
    /// </summary>
    [DataContract]
    public partial class Game : IEntity<string>
    {
        /// <summary>
        /// Primary key
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// State progress of the game -- e.g., in progress, or done
        /// </summary>
        public enum GameState
        {
            /// <summary>
            /// Game is still in progress.
            /// </summary>
            [Display(Name = "In Progress")]
            IN_PROGRESS,

            /// <summary>
            /// Game has finished.
            /// </summary>
            [Display(Name = "Done")]
            DONE
        }

        /// <summary>
        /// State progress of the game
        /// </summary>
        [Required]
        public GameState State { get; set; }

        // -------------
        // Relationships

        /// <summary>
        /// Player names
        /// </summary>
        [Required]
        public virtual ICollection<Player> Players { get; set; }

        /// <summary>
        /// Game board
        /// </summary>
        public virtual GameBoard GameBoard { get; set; }
    }
}
