/*
 * 98Point6 Drop-Token
 *
 * At-home interview implementation of \"98Point6 Drop-Token\" homework assignment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: aaron@focuszonedevelopment.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ConnectFour.DataLayer.Models
{
    /// <summary>
    /// Details of a game in progress
    /// </summary>
    [DataContract]
    public partial class Game
    {
        /// <summary>
        /// Primary key
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// State progress of the game -- e.g., in progress, or done
        /// </summary>
        public enum GameState
        {
            /// <summary>
            /// Game is still in progress.
            /// </summary>
            [Display(Name = "In Progress")]
            IN_PROGRESS,

            /// <summary>
            /// Game has finished.
            /// </summary>
            [Display(Name = "Done")]
            DONE
        }

        /// <summary>
        /// Player names
        /// </summary>
        [Required]
        public IList<string> Players { get; set; }

        /// <summary>
        /// State progress of the game
        /// </summary>
        [Required]
        public GameState State { get; set; }

        /// <summary>
        /// Moves made during this game
        /// </summary>
        public GameMove[] Moves { get; set; }

        public GameBoard Board { get; set; }
    }

    public class GameBoard
    {
        /// <summary>
        /// Two-dimensional game board representing rows and columns.
        /// Default value of null means no piece is yet played in that location.
        /// Otherwise, the value is equal to the player index in the containing game.
        /// </summary>
        /// <remarks>This is allocated as [columns][rows] instead of the more conventional [rows][columns]
        /// since the style of this game largely cares more about columns than rows, so indexing is easier.
        /// </remarks>
        private readonly int?[,] _board;

        private readonly int _columns;
        private readonly int _rows;

        /// <summary>
        /// Player ID of the winning player, if any.
        /// </summary>
        private int _winner = NO_WINNER;
        public const int NO_WINNER = -1;

        public GameBoard(int rows, int columns)
        {
            if (rows <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(rows));
            }

            if (columns <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(columns));
            }

            _rows = rows;
            _columns = columns;

            _board = new int?[_columns, _rows];
        }

        /// <summary>
        /// Drops a <paramref name="player"/> token in the specified <paramref name="column"/>.
        /// </summary>
        /// <param name="column">Column to drop the token into</param>
        /// <param name="player">Player dropping the token</param>
        /// <returns>true if the token was successfully played; otherwise false</returns>
        public bool DropToken(int column, int player)
        {
            // Find the first empty row to place the token
            for (int row = 0; row < _rows; row++)
            {
                // If it doesn't have a value, there's no token -- place the token
                if (!_board[column, row].HasValue)
                {
                    _board[column, row] = player;
                    return true;
                }
            }

            // Couldn't find an empty row to place the token
            return false;
        }

        /// <summary>
        /// Checks if a winner is found with a horizontal ("row") victory.
        /// </summary>
        /// <returns>The player ID if a winner is found; otherwise NO_WINNER</returns>
        private int CheckRowWin()
        {
            // Horizontal check
            for (int row = 0; row < _rows; row++)
            {
                var firstToken = _board[0, row];
                int col;
                for (col = 1; col < _columns; col++)
                {
                    // If there's no token, the chain is broken!
                    if (!_board[col, row].HasValue)
                    {
                        break;
                    }

                    // Different player found; the chain is broken!
                    if (_board[col, row].Value != firstToken)
                    {
                        break;
                    }
                }

                // We checked the whole row and didn't find a break -- WINNER!
                if (col == _columns)
                {
                    return _board[_columns, row].Value;
                }
            }

            // Checked every row and found nothing
            return NO_WINNER;
        }

        /// <summary>
        /// Checks if a winner is found with a vertical ("column") victory.
        /// </summary>
        /// <returns>The player ID if a winner is found; otherwise NO_WINNER</returns>
        private int CheckColumnWin()
        {
            for (int col = 0; col < _columns; col++)
            {
                var firstToken = _board[col, 0];
                int row;
                for (row = 1; row < _rows; row++)
                {
                    // If there's no token, the chain is broken!
                    if (!_board[col, row].HasValue)
                    {
                        break;
                    }

                    // Different player found; the chain is broken!
                    if (_board[col, row].Value != firstToken)
                    {
                        break;
                    }
                }

                // We checked the whole column and didn't find a break -- WINNER!
                if (row == _rows)
                {
                    return _board[col, _rows].Value;
                }
            }

            // Checked every column and found nothing
            return NO_WINNER;
        }

        /// <summary>
        /// Checks if a winner is found with a diagonal victory.
        /// </summary>
        /// <returns>The player ID if a winner is found; otherwise NO_WINNER</returns>
        private int CheckDiagonalWin()
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Attempts to find a game winner, if any.
        /// </summary>
        /// <returns>The player ID if a winner is found; otherwise NO_WINNER</returns>
        public int GetWinner()
        {
            // If we've already calculated a winner and nothing has changed, don't waste the time to find it again
            if (_winner != NO_WINNER)
            {
                return _winner;
            }

            _winner = CheckColumnWin();
            if (_winner != NO_WINNER)
            {
                return _winner;
            }

            _winner = CheckRowWin();
            if (_winner != NO_WINNER)
            {
                return _winner;
            }

            _winner = CheckDiagonalWin();
            if (_winner != NO_WINNER)
            {
                return _winner;
            }

            return NO_WINNER;
        }

        /// <summary>
        /// Checks whether the game has a winning player
        /// </summary>
        /// <returns>true if the game has a winning player, otherwise false</returns>
        public bool HasWinner() => GetWinner() != NO_WINNER;

        /// <summary>
        /// Checks if the entire game board is full (i.e., game is over with no winner)
        /// </summary>
        /// <returns>true if all columns are full; otherwise false</returns>
        public bool IsFull()
        {
            // Check the top row of every column -- if they all have a value, then the board is full
            for (int col = 0; col < _columns; col++)
            {
                if (!_board[col, _rows].HasValue)
                {
                    return false;
                }
            }
            return true;
        }
    }
}
